### create new Report
POST http://localhost:3000/reports
content-type: application/json

{
    "make": "toyota",
    "model": "corolla",
    "year": 1980,
    "mileage": 90000,
    "lng": 0,
    "lat": 0,
    "price": 9000
}

### Approve report
PATCH http://localhost:3000/reports/8
content-type: application/json

{
    "approved": true
}

### Get Estimate 
GET http://localhost:3000/reports?make=toyota&model=corolla&lat=0&lng=0&mileage=100000&year=1980

